---
- name: Using Zabbix collection
  hosts: all
  connection: local

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Set credentials to access Zabbix Server API
      ansible.builtin.set_fact:
        ansible_user: "{{ lookup('env','ZABBIX_USER') }}"
        ansible_httpapi_pass: "{{ lookup('env','ZABBIX_PASSWORD') }}"

    - name: Create host groups
      community.zabbix.zabbix_group:
        state: present
        host_groups:
          - Internet servers
  
    - name: Create a host for cert monitoring
      community.zabbix.zabbix_host:
        host_name: "{{ inventory_hostname }}"
        visible_name: Cert - {{ inventory_hostname }}
        description: Monitoring SSL cert
        host_groups:
          - Internet servers
        link_templates:
          - Website certificate by Zabbix agent 2
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 127.0.0.1
            dns: "{{ inventory_hostname }}"
            port: "10050"
        macros:
          - macro: "{$CERT.WEBSITE.HOSTNAME}"
            value: "{{ inventory_hostname }}"
        tags:
          - tag: Security
            value: SSL
...
