- name: Using Zabbix collection
  hosts: localhost
  collections:
    - community.zabbix
  tasks:
    - name: Create a SmEjDiL host or update
      zabbix_host:
        server_url: https://zabbix.pfsense.cz
        login_user: "{{ lookup('env','ZABBIX_USER') }}"
        login_password: "{{ lookup('env','ZABBIX_PASSWORD') }}"
        host_name: www.smejdil.cz
        visible_name: Webserver SmEjDiL.cz
        description: Monitoring SmEjDIL.cz webserver
        host_groups:
         - Public/WWW
        link_templates:
         - Template Module ICMP Ping
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
         - type: 1
           main: 1
           useip: 1
           ip: 2a03:b280::216:3eff:fe00:328
           dns: "www.smejdil.cz"
           port: "10050"
        tags:
          - tag: OS
            value: FreeBSD
          - tag: App
            value: Webserver