- name: Using Zabbix collection
  hosts: localhost
  collections:
    - community.zabbix
  tasks:
    - name: Create host groups
      zabbix_group:
        server_url: https://zabbix.pfsense.cz
        login_user: "{{ lookup('env','ZABBIX_USER') }}"
        login_password: "{{ lookup('env','ZABBIX_PASSWORD') }}"
        state: present
        host_groups:
          - Public/WWW