---
- name: Create a jmx host or update
  zabbix_host:
    server_url: "{{ server_url }}"
    login_user: "{{ lookup('env','ZABBIX_USER') }}"
    login_password: "{{ lookup('env','ZABBIX_PASSWORD') }}"
    host_name: openjdk.java.net
    visible_name: Webserver openjdk.java.net
    description: Monitoring projekt openjdk.java.net
    host_groups:
     - Public/WWW
    link_templates:
     - Template Module ICMP Ping
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 4
        main: 1
        useip: 1
        ip: 137.254.56.60
        dns: "openjdk.java.net"
        port: "12345"
    tags:
      - tag: OS
        value: Linux
      - tag: App
        value: Webserver
