---
- name: create a new zabbix user.
  zabbix_user:
    server_url: "{{ server_url }}"
    login_user: "{{ lookup('env','ZABBIX_USER') }}"
    login_password: "{{ lookup('env','ZABBIX_PASSWORD') }}"
    alias: tester
    name: Tester
    surname: Testovic
    usrgrps:
      - Public/Goolge
      - Private/LM.NET
    passwd: 123456
    lang: en_GB
    theme: dark-theme
    autologin: no
    autologout: '0'
    refresh: '30'
    rows_per_page: '50'
    after_login_url: ''
    user_medias:
      - mediatype: Email
        sendto: zabbix@seznam.cz
        period: 1-7,00:00-24:00
        severity:
          not_classified: no
          information: no
          warning: yes
          average: yes
          high: yes
          disaster: yes
        active: no
    type: Zabbix user
    state: present
